require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - app/channels/story_channel.rb

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
