version: '3.1'

services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - sw-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    ports:
      - 6379:6379
    volumes:
      - sw-redis:/var/lib/redis/data

volumes:
  sw-postgres:
  sw-redis:
